others:
  color:
  - Red
  - Blue
  - Green
  - Yellow
  - Black
  - White
  - Purple
  - Orange
  - Brown
  - Gray
  - Cyan
  - Lime
  - Pink
  - Gold
  - Teal
  - Maroon
  - Navy
  - Olive
  - Silver
  - Violet
path:
  assetfolder: D:/research/dataset/.objaverse/hf-objaverse-v1
  metaurbanasset: D:/research/MetaVQA/metaurban/assets/models/test
  metaurbanassetgltf: D:/research/dataset/pede
  parentfolder: D:/research/dataset
  raw_assetfolder: D:/research/dataset/raw_asset_folder
  subfolders:
    adj_parameter_folder: adj_parameter_folder
    all_tag_path: all_tag_list.json
    filter_asset_path_folder: filter_asset_path_folder
    ignore_adj_folder: ignore_adj_folder
    layout_static_info_folder: layout_static_info_folder
    match_uid_path_folder: match_uid_path_folder
    raw_asset_path_folder: raw_asset_path_folder
tag:
  istaglist: true
  selecttag: car
  tag: car
  taglist: ["sportcars", "3dfreecarmodel", "blackcar", "luxary-car", "urbancar", "car-moscvich",
            "nypd-car", "motorcar", "car-audi-vehicle-luxurycar-cars", "moderncar", "car-vehicle",
            ]
type:
  guidance_objects:
  - Cone
  - StopSign
  - Warning
  - Wall
  - NoAccess
  - TrafficLight
  structures:
  - Tollgate
  - BusStop
  - Curbside
  - GasStation
  - FireHose
  - Parking Meter
  two_wheeled:
  - Bike
  - Motorcycle
  vehicle:
  - SUV
  - Sedan
  - Truck
  - SportCar
  - Jeep
  - Pickup
  - Junk Car
  - Hatchback
  - Coupe
typeinfo:
  ? ''
  : bounding_box:
    - - 1.4220118522644043
      - 2.4616129398345947
    - - 1.4220118522644043
      - -2.463218927383423
    - - -1.4257817268371582
      - -2.463218927383423
    - - -1.4257817268371582
      - 2.4616129398345947
    center:
    - -0.0018849372863769531
    - -0.0008029937744140625
    length: 2.8477935791015625
    width: 4.924831867218018
  Bike:
    bounding_box:
    - - 1.1214572191238403
      - 0.4881875216960907
    - - 1.1214572191238403
      - -0.48748332262039185
    - - -1.122035026550293
      - -0.48748332262039185
    - - -1.122035026550293
      - 0.4881875216960907
    center:
    - -0.00028890371322631836
    - 0.00035209953784942627
    length: 2.2434922456741333
    width: 0.9756708443164825
  BusStop:
    bounding_box:
    - - 1.3032584190368652
      - 3.2173943519592285
    - - 1.3032584190368652
      - -2.040933609008789
    - - -1.347522258758545
      - -2.040933609008789
    - - -1.347522258758545
      - 3.2173943519592285
    center:
    - -0.022131919860839844
    - 0.5882303714752197
    length: 2.65078067779541
    width: 5.258327960968018
  Cone:
    bounding_box:
    - - 0.3924295902252197
      - 0.392631471157074
    - - 0.3924295902252197
      - -0.3917238712310791
    - - -0.3919258713722229
      - -0.3917238712310791
    - - -0.3919258713722229
      - 0.392631471157074
    center:
    - 0.0002518594264984131
    - 0.0004537999629974365
    length: 0.7843554615974426
    width: 0.7843553423881531
  Hatchback:
    bounding_box:
    - - 2.4702351093292236
      - 1.1965457201004028
    - - 2.4702351093292236
      - -1.2415012121200562
    - - -2.421722412109375
      - -1.2415012121200562
    - - -2.421722412109375
      - 1.1965457201004028
    center:
    - 0.024256348609924316
    - -0.02247774600982666
    length: 4.891957521438599
    width: 2.438046932220459
  Motorcycle:
    bounding_box:
    - - 1.0478734970092773
      - 0.4211578667163849
    - - 1.0478734970092773
      - -0.4197881519794464
    - - -1.0477899312973022
      - -0.4197881519794464
    - - -1.0477899312973022
      - 0.4211578667163849
    center:
    - 4.178285598754883e-05
    - 0.0006848573684692383
    length: 2.0956634283065796
    width: 0.8409460186958313
  NoAccess:
    bounding_box:
    - - 0.5975431799888611
      - 1.7264913320541382
    - - 0.5975431799888611
      - -1.724768042564392
    - - -0.5986411571502686
      - -1.724768042564392
    - - -0.5986411571502686
      - 1.7264913320541382
    center:
    - -0.0005489885807037354
    - 0.0008616447448730469
    length: 1.1961843371391296
    width: 3.4512593746185303
  SUV:
    bounding_box:
    - - 2.445617198944092
      - 1.2172163724899292
    - - 2.445617198944092
      - -1.220836877822876
    - - -2.446354389190674
      - -1.220836877822876
    - - -2.446354389190674
      - 1.2172163724899292
    center:
    - -0.0003685951232910156
    - -0.0018102526664733887
    length: 4.891971588134766
    width: 2.438053250312805
  SportCar:
    bounding_box:
    - - 2.2906653881073
      - 1.0854926109313965
    - - 2.2906653881073
      - -1.0869956016540527
    - - -2.2900233268737793
      - -1.0869956016540527
    - - -2.2900233268737793
      - 1.0854926109313965
    center:
    - 0.0003210306167602539
    - -0.000751495361328125
    length: 4.580688714981079
    width: 2.172488212585449
  StopSign:
    bounding_box:
    - - 0.07454484701156616
      - 0.7002328038215637
    - - 0.07454484701156616
      - -0.6865848302841187
    - - -0.07454782724380493
      - -0.6865848302841187
    - - -0.07454782724380493
      - 0.7002328038215637
    center:
    - -1.4901161193847656e-06
    - 0.006823986768722534
    length: 0.1490926742553711
    width: 1.3868176341056824
  TrafficLight:
    bounding_box:
    - - 0.32314467430114746
      - 3.66133975982666
    - - 0.32314467430114746
      - -3.658132314682007
    - - -0.2902834117412567
      - -3.658132314682007
    - - -0.2902834117412567
      - 3.66133975982666
    center:
    - 0.016430631279945374
    - 0.0016037225723266602
    length: 0.6134280860424042
    width: 7.319472074508667
  Truck:
    bounding_box:
    - - 2.459498882293701
      - 0.8482210040092468
    - - 2.459498882293701
      - -0.8475002646446228
    - - -2.454247236251831
      - -0.8475002646446228
    - - -2.454247236251831
      - 0.8482210040092468
    center:
    - 0.0026258230209350586
    - 0.0003603696823120117
    length: 4.913746118545532
    width: 1.6957212686538696
  test:
    height: 10
    width: 10
